Repository AY2324S1-CS2113-T17-2/tp, pull requests merged in 2023-10, with the labels that each got.

#44 Edit classes v1.0
  src/main/java/seedu/duke/data/Menu.java
  src/main/java/seedu/duke/data/dish/Dish.java
  src/main/java/seedu/duke/data/dish/Ingredient.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Task

#98 73 implement help command
  src/main/java/seedu/cafectrl/command/HelpCommand.java
  src/main/java/seedu/cafectrl/command/ListMenuCommand.java
  src/main/java/seedu/cafectrl/parser/Parser.java
  src/main/java/seedu/cafectrl/ui/Messages.java
  src/main/java/seedu/cafectrl/ui/Ui.java
  src/test/java/seedu/cafectrl/command/HelpCommandTest.java
  src/test/java/seedu/cafectrl/command/ListMenuCommandTest.java
Labels: type.Task, priority.Medium

#95 Task 90 and Task 91 Implement View Total Stock and Buy Ingredients
  src/main/java/seedu/cafectrl/CafeCtrl.java
  src/main/java/seedu/cafectrl/command/AddDishCommand.java
  src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
  src/main/java/seedu/cafectrl/command/Command.java
  src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
  src/main/java/seedu/cafectrl/command/EditPriceCommand.java
  src/main/java/seedu/cafectrl/command/ExitCommand.java
  src/main/java/seedu/cafectrl/command/HelpCommand.java
  src/main/java/seedu/cafectrl/command/IncorrectCommand.java
  src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
  src/main/java/seedu/cafectrl/command/ListMenuCommand.java
  src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
  src/main/java/seedu/cafectrl/data/Pantry.java
  src/main/java/seedu/cafectrl/data/dish/Ingredient.java
  src/main/java/seedu/cafectrl/parser/Parser.java
  src/main/java/seedu/cafectrl/ui/Messages.java
  src/main/java/seedu/cafectrl/ui/Ui.java
  src/test/java/seedu/cafectrl/command/AddDishCommandTest.java
  src/test/java/seedu/cafectrl/command/DeleteDishCommandTest.java
  src/test/java/seedu/cafectrl/command/EditPriceCommandTest.java
  src/test/java/seedu/cafectrl/command/HelpCommandTest.java
  src/test/java/seedu/cafectrl/command/ListIngredientCommandTest.java
  src/test/java/seedu/cafectrl/command/ListMenuCommandTest.java
  src/test/java/seedu/cafectrl/parser/ParserTest.java
Labels: type.Task, priority.High

#96 Task 92, Task 93 Implement stock checking of ingredients in Pantry class
  src/main/java/seedu/cafectrl/CafeCtrl.java
  src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
  src/main/java/seedu/cafectrl/data/Pantry.java
  src/main/java/seedu/cafectrl/data/dish/Ingredient.java
  src/main/java/seedu/cafectrl/ui/Ui.java
  src/test/java/seedu/cafectrl/command/AddDishCommandTest.java
  src/test/java/seedu/cafectrl/command/DeleteDishCommandTest.java
  src/test/java/seedu/cafectrl/command/EditPriceCommandTest.java
  src/test/java/seedu/cafectrl/command/HelpCommandTest.java
  src/test/java/seedu/cafectrl/command/ListIngredientCommandTest.java
  src/test/java/seedu/cafectrl/command/ListMenuCommandTest.java
  src/test/java/seedu/cafectrl/parser/ParserTest.java
Labels: type.Task, priority.High

#165 Update DG: parser class and help command
  docs/DeveloperGuide.md
  docs/diagrams/class/Parser.puml
  docs/diagrams/sequence/EditPriceCommand_execute.puml
  docs/diagrams/sequence/HelpCommand_execute.puml
  docs/diagrams/sequence/Parser.puml
  docs/images/class/Parser.png
  docs/images/sequence/EditPriceCommand_execute.png
  docs/images/sequence/HelpCommand_execute.png
  docs/images/sequence/Parser.png
Labels: type.Task, priority.High

#161 Task 146, Create encoding and decoding to text file in menu storage
  .gitignore
  src/main/java/seedu/cafectrl/data/Pantry.java
  src/main/java/seedu/cafectrl/parser/Parser.java
  src/main/java/seedu/cafectrl/storage/Decoder.java
  src/main/java/seedu/cafectrl/storage/Encoder.java
  src/main/java/seedu/cafectrl/storage/FileManager.java
  src/main/java/seedu/cafectrl/storage/Storage.java
Labels: type.Story, type.Task, priority.High

#177 176 UG help edit price
  docs/UserGuide.md
  src/main/java/seedu/cafectrl/CafeCtrl.java
  src/main/java/seedu/cafectrl/parser/Parser.java
  src/main/java/seedu/cafectrl/parser/ParserUtil.java
  src/test/java/seedu/cafectrl/parser/ParserTest.java
Labels: type.Task, priority.High
